name: cobalt

services:
  cobalt:
    image: ghcr.io/imputnet/cobalt:11.7.1-a636575@sha256:df14a3b3fe4390d4e1c2d4761ed58981d34aa5fc82d0df2091bab890e7dfaa8b
    container_name: cobalt
    restart: unless-stopped
    stop_grace_period: 40s
    network_mode: bridge
    environment:
      API_URL: CHANGEME_API_URL
    ports:
      - target: 9000
        published: "8417"
        protocol: tcp

    deploy:
      resources:
        limits:
          cpus: "2.00"
          memory: 1024M
        reservations:
          cpus: "0.00"
          memory: 128M

  cobalt-web:
    image: ghcr.io/spotdemo4/cobalt-web:latest@sha256:c61bcdf8b45997f91a9e97588c743a42b1b1d1a6c69e8de75c8c3874e3853b62
    container_name: cobalt-web
    restart: unless-stopped
    stop_grace_period: 40s
    network_mode: bridge
    depends_on:
      - cobalt
    environment:
      WEB_DEFAULT_API: CHANGEME_API_URL
      WEB_HOST: CHANGEME_WEB_HOST
    ports:
      - target: 8787
        published: "8418"
        protocol: tcp

    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 2048M
        reservations:
          cpus: "0.00"
          memory: 256M

x-casaos:
  id: com.hiraappstore.cobalt
  main: cobalt-web
  icon: https://Zimaos.hsinghhira.me/apps/com.hiraappstore.cobalt/assets/icon.png
  title:
    en_US: Cobalt
  index: /
  port_map: "8418"
  scheme: http
  version: "11.7.1"
