name: vert

services:
  vert:
    image: ghcr.io/vert-sh/vert:latest@sha256:d1920cad7f7405335665900ec45f907a63ae2552f7c5f4c8b86682a869750287
    container_name: vert
    restart: unless-stopped
    stop_grace_period: 40s
    network_mode: bridge
    ports:
      - target: 80
        published: "8420"
        protocol: tcp
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 256M
        reservations:
          cpus: "0.00"
          memory: 64M
x-casaos:
  id: com.hiraappstore.vert
  main: vert
  icon: https://Zimaos.hsinghhira.me/apps/com.hiraappstore.vert/assets/icon.png
  title:
    en_US: VERT
  index: /
  port_map: "8420"
  scheme: http
