name: searxng

services:
  searxng:
    image: docker.io/searxng/searxng:2026.8.10-0a118066d@sha256:0e98a7be738750a2cce353b64b7638cb55ec1784ea6993fbb512aad5a3273bd7
    container_name: searxng
    restart: unless-stopped
    stop_grace_period: 40s
    depends_on:
      - searxng-valkey
    environment:
      - SEARXNG_BASE_URL=http://localhost:8402/
    ports:
      - target: 8080
        published: "8402"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /etc/searxng
        bind:
          create_host_path: true
      - type: bind
        source: /DATA/AppData/$AppID/data
        target: /var/cache/searxng
        bind:
          create_host_path: true
    networks:
      - searxng_network
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 128M
  searxng-valkey:
    image: docker.io/valkey/valkey:9-alpine@sha256:dd021e69e0a204fbb25b39c332c3dd61d51853d0a67e34f523cf1e1ab15fe478
    container_name: searxng-valkey
    restart: unless-stopped
    stop_grace_period: 40s
    command: valkey-server --save 30 1 --loglevel warning
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/valkey
        target: /data
        bind:
          create_host_path: true
    networks:
      - searxng_network
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 128M
        reservations:
          cpus: "0.00"
          memory: 64M
networks:
  searxng_network:
    driver: bridge

x-casaos:
  id: com.hiraappstore.searxng
  main: searxng
  icon: https://Zimaos.hsinghhira.me/apps/com.hiraappstore.searxng/assets/icon.png
  title:
    en_US: SearXNG
  index: /
  port_map: "8402"
  scheme: http
  version: "2026.8.10-0a118066d"
